### ISSUE TITLE
Provide EPICS PVs as constructor kwargs

### ISSUE THREAD

**Issue by prjemian** [prjemian/hklpy2#21]
As described [elsewhere](https://github.com/BCDA-APS/BITS/pull/32#issuecomment-2591017336), provide EPICS PVs as constructor kwargs.  This facilitates device creation from a a file description.

As copied from that issue:

## diffractometer

While the `hklpy` package provides a 6-circle diffractometer, it does not provide a class with name substitutions for the motor axes.  (That's a DIY feature for improvement in a future version.)  We'll have to make some local code that provides motor name substitutions as kwargs.

Here's an example of local support code:

```py
"""Diffractometers"""

import hkl
from ophyd import Component
from ophyd import EpicsMotor
from ophyd import EpicsSignalRO
from ophyd import FormattedComponent as FCpt

class SixCircle(hkl.SimMixin, hkl.E6C):
    """
    Our 6-circle.  Eulerian.

    Energy obtained (RO) from monochromator.
    """

    # the reciprocal axes are defined by SimMixin

    mu = FCpt(EpicsMotor, "{prefix}{m_mu}", kind="hinted", labels=["motor"])
    omega = FCpt(EpicsMotor, "{prefix}{m_omega}", kind="hinted", labels=["motor"])
    chi = FCpt(EpicsMotor, "{prefix}{m_chi}", kind="hinted", labels=["motor"])
    phi = FCpt(EpicsMotor, "{prefix}{m_phi}", kind="hinted", labels=["motor"])
    gamma = FCpt(EpicsMotor, "{prefix}{m_gamma}", kind="hinted", labels=["motor"])
    delta = FCpt(EpicsMotor, "{prefix}{m_delta}", kind="hinted", labels=["motor"])

    energy = Component(EpicsSignalRO, "BraggERdbkAO", kind="hinted", labels=["energy"])
    energy_units = Component(EpicsSignalRO, "BraggERdbkAO.EGU", kind="config")

    def __init__(  # noqa D107
        self,
        prefix,
        *,
        m_mu="",
        m_omega="",
        m_chi="",
        m_phi="",
        m_gamma="",
        m_delta="",
        **kwargs,
    ):
        self.m_mu = m_mu
        self.m_omega = m_omega
        self.m_chi = m_chi
        self.m_phi = m_phi
        self.m_gamma = m_gamma
        self.m_delta = m_delta
        super().__init__(prefix, **kwargs)
```

Here's the device:

```yaml
instrument.devices.diffractometers.SixCircle:
  - name: sixc
    prefix: "gp:"
    labels: ["diffractometer"]
    # No defined motor assignments, pick different than fourc (m29-32)
    m_mu: m23
    m_omega: m24
    m_chi: m25
    m_phi: m26
    m_gamma: m27
    m_delta: m28
```

This is the general pattern to declare ophyd-style devices in YAML files:

- when code (classes, factory functions) is provided by a package:
  - refer to the package class (or function) directly in the YAML file
- when local customization is needed (new support or modify a packaged class):
  - create local custom code that defines the class or factory
  - refer to local custom code in the YAML file
